name: baby_feeding
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  flutter_vector_icons: ^2.0.0
  smooth_page_indicator: ^1.1.0
  pinput: ^2.2.31
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^4.8.0
  firebase_core_web: ^2.6.0
  firebase_auth: ^4.6.3
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  country_picker: ^2.0.20
  sqflite: ^2.2.8+4
  flutter_datetime_picker_plus: ^2.0.1
  intl: ^0.19.0
  flutter_local_notifications: ^14.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6





flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
